### ISSUE TITLE
Design MySQl schema with/for users, workers and clients

### ISSUE THREAD

**Issue by kxprim** [FatalBadgers/FatalBadgers#3]
There needs to be 4 tables (up for debate):
- users
- workers
- jobs
- replies
- clients

Create test (Karma)

**Comment by yanarchy** [comment]
We decided upon these following tables:
-clients
-workers
-jobs
-worker_open_jobs (join table)
-client_reviews
-worker_reviews

**Comment by scottrice10** [comment]
A schema.sql file was added to the root directory, but Sequelize does not use it to create the databases.
