### ISSUE TITLE
Create login page view, route, and controller.

### ISSUE THREAD

**Issue by yanarchy** [FatalBadgers/FatalBadgers#46]
Angular, HTML
Sign-in view (i.e. the form) should change depending on if user is client or worker.

This tasks includes the following sub-tasks:
- Create login page view, route, and controller.
- Create signup page view, route, and controller.
  - This should include dynamic form fields for client or worker account creation.
- Create account settings view, route, and controller.
- Create authentication factory to process auth services.

**Comment by tmartin1** [comment]
All sub-tasks have been given their own gh issue ticket and this issue now only concerns the login page, route, and controller.
